import sys, os, subprocess, time, json
import psycopg2
from playwright.sync_api import sync_playwright
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mock_sb

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "index.html")
PATH = "file://" + os.path.abspath(PAGE)
UMD = "/tmp/sbjs/inject.js"
SR = "document.querySelector('.pt-host').shadowRoot"
PNG = "/tmp/e2e.png"
ADMIN_PW = "CHANGE-THIS-PASSWORD"
DSN = mock_sb.DSN
fails, errors = [], []
def ok(c, m):
    print(("OK   " if c else "FAIL ") + m)
    if not c: fails.append(m)

# fresh database with the real setup script
PSQL = ["psql", "-h", "/tmp/pg16", "-p", "5433", "-U", "postgres", "-q", "-v", "ON_ERROR_STOP=1"]
subprocess.run(["dropdb", "-h", "/tmp/pg16", "-p", "5433", "-U", "postgres", "--if-exists", "q29"], check=True)
subprocess.run(["createdb", "-h", "/tmp/pg16", "-p", "5433", "-U", "postgres", "q29"], check=True)
subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "sb_shim.sql")], check=True, capture_output=True)
subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_setup.sql")], check=True, capture_output=True)
from PIL import Image
Image.new("RGB", (2400, 1600), (180, 140, 20)).save(PNG)
srv = mock_sb.serve(54321)
def sql(q, a=()):
    c = psycopg2.connect(DSN); cur = c.cursor(); cur.execute(q, a); r = cur.fetchall() if cur.description else None; c.commit(); c.close(); return r

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 900, "height": 1000})
    ctx.add_init_script(script="window.Q29_DB={url:'http://127.0.0.1:54321',key:'sb_publishable_test'};")
    ctx.add_init_script(path=UMD)
    page = ctx.new_page()
    page.on("pageerror", lambda e: errors.append(str(e)))
    page.on("console", lambda m: m.type == "error" and "fonts.googleapis" not in m.text and "ERR_" not in m.text and "status of 4" not in m.text and errors.append("console: " + m.text))
    page.goto(PATH); page.wait_for_timeout(400)
    ev = page.evaluate
    L = page.locator
    def app(): return ev(f"{SR}.querySelector('#app').innerText")
    def wait_loaded(): page.wait_for_function(f"()=>{{const r=document.querySelector('.pt-host');return r&&!r.shadowRoot.querySelector('#app').innerText.includes('جارٍ تحميل')}}", timeout=15000); page.wait_for_timeout(250)
    def login(u, pw):
        page.click("#coordBtn"); page.wait_for_timeout(200); page.fill("#lgU", u); page.fill("#lgP", pw); page.click("#lgGo"); wait_loaded()
    def out(): ev(f"{SR}.querySelector('#abOut').click()"); page.wait_for_timeout(600)
    def tab(t): ev(f"()=>[...{SR}.querySelectorAll('[data-at]')].find(b=>b.textContent.trim()==='{t}').click()"); page.wait_for_timeout(300)
    def toast(): return ev(f"()=>[...{SR}.querySelectorAll('.toast')].map(t=>t.textContent).join(' | ')")
    def clr(): ev(f"()=>{SR}.querySelectorAll('.toast').forEach(t=>t.remove())")
    def wait_toast(txt, t=10000): page.wait_for_function(f"()=>[...{SR}.querySelectorAll('.toast')].some(x=>x.textContent.includes('{txt}'))", timeout=t)

    ok(ev("!!document.querySelector('.lg-acc')") is False, "demo accounts list is removed from the login dialog in database mode")
    # ---------- 1. admin creates entities (with and without reviewer)
    login("admin", ADMIN_PW)
    ok("لوحة المشرف" in app(), "admin logs in with the password from the setup script")
    ok(ev(f"{SR}.querySelector('#tools').hidden") is True, "date simulator hidden (real date used)")
    tab("الجهات والمنسقون")
    def add_entity(name, coord, phone, user, pw, rev=None):
        clr(); ev(f"{SR}.querySelector('#addEnt').click()"); page.wait_for_timeout(300)
        L("#en").fill(name); L("#ec").fill(coord); L("#ep").fill(phone); L("#eu").fill(user); L("#epw").fill(pw)
        if rev: L("#rvn").fill(rev[0]); L("#rvp").fill(rev[1]); L("#rvu").fill(rev[2]); L("#rvpw").fill(rev[3])
        ev(f"{SR}.querySelector('#ef button[type=submit]').click()"); wait_toast("أُضيفت الجهة")
    add_entity("مركز النور التجريبي", "أحمد سالم الكندري", "55500011", "noor.test", "noor1234", ("سارة علي العنزي", "55500022", "sara.test", "sara1234"))
    add_entity("مدرسة الفجر التجريبية", "خالد يوسف المطيري", "55500033", "fajr.test", "fajr1234")
    r = sql("select e.username, e.rev_username, (select count(*) from members m where m.ent_id=e.id) from entities e order by created_at")
    ok(r == [("noor.test", "sara.test", 2), ("fajr.test", None, 1)], f"entities + accounts stored in the database {r}")
    t = app(); ok("مركز النور التجريبي" in t and "مدرسة الفجر التجريبية" in t, "entities listed for the admin")
    out()

    # ---------- 2. coordinator registers a complete candidate with a document
    login("noor.test", "noor1234")
    t = app(); ok("مركز النور التجريبي" in t and "قائمة مرشحي الجهة" in t, "coordinator logs in and sees own entity")
    ev(f"{SR}.querySelector('#abHome').click()"); page.wait_for_timeout(500)
    ok(ev("!document.querySelector('.pt-host')"), "back to the guide")
    page.click("#coordBtn"); wait_loaded()
    ok("قائمة مرشحي الجهة" in app() and ev("document.querySelector('.lg-wrap').hidden"), "reopening the portal keeps the coordinator signed in (no password needed)")
    def new_candidate(name, cid, phone, upload=True):
        clr(); ev(f"{SR}.querySelector('#add').click()"); page.wait_for_timeout(300)
        L("#fn").fill(name); L("#fc").fill(cid); page.wait_for_timeout(300)
        L("#fph").fill(phone); L("#far").fill("منطقة تجريبية"); L("#fbl").fill("3"); L("#fst2").fill("12"); L("#fbd").fill("7")
        ev(f"()=>{{const s={SR}.querySelector('#fs');const o=[...s.options].find(o=>o.value&&!o.disabled);s.value=o.value;s.dispatchEvent(new Event('change'))}}"); page.wait_for_timeout(250)
        if ev(f"!!{SR}.querySelector('[data-jq=last]')"): ev(f"{SR}.querySelector('[data-jq=last]').click()"); page.wait_for_timeout(250)
        if upload: L("input[data-doc='cid']").first.set_input_files(PNG); page.wait_for_timeout(1200)
        ev(f"()=>{{const a={SR}.querySelector('#fag');if(!a.checked)a.click()}}"); page.wait_for_timeout(150)
        ev(f"{SR}.querySelector('#cf button[type=submit]').click()")
    new_candidate("محمد عبدالله سالم الرشيدي", "290010212345", "51234567")
    wait_toast("أُرسلت للمراجعة")
    r = sql("select status, data->>'name', docs from candidates where cid='290010212345'")
    ok(r and r[0][0] == "pending" and r[0][1] == "محمد عبدالله سالم الرشيدي", "complete candidate saved to the database as pending review")
    docs = r[0][2]; path = docs.get("cid", {}).get("path", "")
    blob = mock_sb.FILES.get(("docs", path))
    ok(path.count("/") == 2 and blob is not None, f"civil ID image uploaded to storage in the entity folder: {path}")
    if blob:
        from io import BytesIO
        im = Image.open(BytesIO(blob[0])); ok(blob[1] == "image/jpeg" and max(im.size) <= 1600 and len(blob[0]) < 400_000, f"image compressed before upload ({im.size}, {len(blob[0])//1024} KB)")
    # incomplete -> draft
    new_candidate("نورة فهد سعد العجمي", "295060712345", "51234568", upload=False)
    wait_toast("مسودة")
    ok(sql("select status from candidates where cid='295060712345'") == [("draft",)], "incomplete candidate saved as draft")
    out()

    # ---------- 3. reviewer sees the document through a signed link and approves
    login("sara.test", "sara1234")
    ok("بانتظار مراجعتك" in app(), "reviewer sees the pending box")
    ev(f"()=>[...{SR}.querySelectorAll('#app .mrow')].find(r=>r.innerText.includes('محمد عبدالله')).querySelector('[data-prev]').click()"); page.wait_for_timeout(1500)
    src = ev(f"()=>{{const i={SR}.querySelector('img.doc-th');return i?i.src:''}}")
    ok(src.startswith("http://127.0.0.1:54321/storage/v1/object/sign/docs/"), "document shown via a signed, time-limited link")
    loaded = ev(f"()=>{{const i={SR}.querySelector('img.doc-th');return i&&i.complete&&i.naturalWidth>0}}")
    ok(loaded, "document image actually loads for the reviewer")
    ev(f"{SR}.querySelector('#pback').click()"); page.wait_for_timeout(300)
    ev(f"()=>[...{SR}.querySelectorAll('#app .mrow')].find(r=>r.innerText.includes('محمد عبدالله')).querySelector('[data-appr]').click()"); page.wait_for_timeout(1500)
    r = sql("select status, log from candidates where cid='290010212345'")
    ok(r[0][0] == "approved" and any(l["a"] == "اعتماد" and "سارة" in l["by"] for l in r[0][1]), "approval saved in the database with the action log")
    out()

    # ---------- 4. another entity cannot register the same civil ID
    login("fajr.test", "fajr1234")
    ok("محمد عبدالله" not in app(), "other entity cannot see this entity's candidates")
    new_candidate("محمد عبدالله سالم الرشيدي", "290010212345", "51234569")
    wait_toast("مسجّل مسبقاً")
    ok(sql("select count(*) from candidates where cid='290010212345'") == [(1,)], "duplicate civil ID refused by the database")
    ev(f"{SR}.querySelector('#fc').closest('form') && {SR}.querySelector('#ecancel, #cancel') && {SR}.querySelector('#cancel').click()"); page.wait_for_timeout(300)
    out()

    # ---------- 5. admin sees and returns; data survives a reload
    page.reload(); page.wait_for_timeout(500)
    login("admin", ADMIN_PW)
    tab("المرشحون")
    ok("محمد عبدالله سالم الرشيدي" in app(), "after a page reload the admin sees the approved candidate (data persisted)")
    ev(f"{SR}.querySelector('[data-aret]').click()"); page.wait_for_timeout(200)
    ev(f"{SR}.querySelector('textarea[id^=arn_]').value='الأجزاء غير صحيحة'"); ev(f"{SR}.querySelector('[data-aretok]').click()"); page.wait_for_timeout(1500)
    ok(sql("select status, review_note from candidates where cid='290010212345'") == [("corrected", "الأجزاء غير صحيحة")], "admin return saved to the database")
    # reset coordinator password
    tab("الجهات والمنسقون")
    ev(f"()=>[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('مدرسة الفجر')).querySelector('[data-ee]').click()"); page.wait_for_timeout(300)
    ok(ev(f"{SR}.querySelector('#eu').readOnly") is True, "username can't be changed after the account exists")
    clr(); L("#epw").fill("fajrNEW99"); ev(f"{SR}.querySelector('#ef button[type=submit]').click()"); wait_toast("حُفظت التعديلات")
    out()
    login("fajr.test", "fajr1234"); ok("غير صحيحة" in app(), "old password no longer works")
    L("#lu").fill("fajr.test"); L("#lp").fill("fajrNEW99"); ev(f"{SR}.querySelector('#lf button[type=submit]').click()"); wait_loaded()
    ok("مدرسة الفجر التجريبية" in app(), "new password set by the admin works")
    out()

    # ---------- 6. coordinator sees the returned note, deletes the draft (file cleanup)
    login("noor.test", "noor1234")
    t = app(); ok("استمارات مُعادة للتصحيح" in t and "الأجزاء غير صحيحة" in t and "ملاحظة المشرف" in t, "coordinator sees the admin's return with the note")
    ev(f"()=>[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('نورة فهد')).querySelector('[data-edit]').click()"); page.wait_for_timeout(300)
    clr(); ev(f"{SR}.querySelector('#del').click()"); ev(f"{SR}.querySelector('#del').click()"); wait_toast("حُذف المرشح")
    ok(sql("select count(*) from candidates where cid='295060712345'") == [(0,)], "candidate deletion saved to the database")
    # ---------- 6b. cancel an approved candidate, then restore it
    ev(f"()=>[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('محمد عبدالله سالم الرشيدي')).querySelector('[data-edit]').click()"); page.wait_for_timeout(300)
    ok(ev(f"!{SR}.querySelector('#del')"), "approved candidate cannot be deleted, only cancelled")
    clr(); ev(f"{SR}.querySelector('#cxl').click()"); ev(f"{SR}.querySelector('#cxl').click()"); wait_toast("أُلغي الترشيح")
    r = sql("select status, log from candidates where cid='290010212345'")
    ok(r[0][0] == "cancelled" and r[0][1][-1]["a"] == "إلغاء الترشيح", "cancellation saved in the database with the log")
    ev(f"()=>[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('محمد عبدالله سالم الرشيدي')).querySelector('[data-edit]').click()"); page.wait_for_timeout(300)
    clr(); ev(f"{SR}.querySelector('#restore').click()"); wait_toast("أُرجع الترشيح")
    ok(sql("select status from candidates where cid='290010212345'") == [("draft",)], "restore saved in the database as a draft")
    out()

    # ---------- 6c. announcements center
    login("admin", ADMIN_PW); tab("الإعلانات")
    ok("supabase_update_3.sql" in app(), "admin is told to run the SQL when the announcements table is missing")
    out()
    subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_3.sql")], check=True, capture_output=True)
    subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_3.sql")], check=True, capture_output=True)
    ok(sql("select count(*) from pg_policies where tablename='announcements'") == [(2,)], "announcements SQL is re-runnable and creates its 2 policies")
    login("admin", ADMIN_PW); tab("الإعلانات")
    ok("supabase_update_3.sql" not in app() and "لا توجد إعلانات" in app(), "announcements tab works once the table exists")
    L("#annT").fill("تم تمديد التسجيل حتى 31 أكتوبر"); ev(f"()=>{{const s={SR}.querySelector('#annL');s.value='warn';s.dispatchEvent(new Event('change'))}}")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    ok(sql("select text, level, active from announcements") == [("تم تمديد التسجيل حتى 31 أكتوبر", "warn", True)], "announcement saved in the database")
    out()
    login("noor.test", "noor1234")
    ok("تم تمديد التسجيل حتى 31 أكتوبر" in app() and "تنبيه هام من إدارة المسابقة" in app(), "entity coordinator sees the announcement")
    out()
    login("sara.test", "sara1234")
    ok("تم تمديد التسجيل حتى 31 أكتوبر" in app(), "entity reviewer sees the announcement")
    out()
    # only the admin may write: emulate entity / reviewer sessions at the SQL level
    def as_user(role_name, q):
        uid = sql("select user_id::text from members where role=%s limit 1", (role_name,))[0][0]
        c = psycopg2.connect(DSN); cur = c.cursor()
        try:
            cur.execute("set local role authenticated"); cur.execute("select set_config('request.jwt.claim.sub', %s, true)", (uid,))
            cur.execute(q); n = cur.rowcount; c.commit(); return ("ok", n)
        except psycopg2.Error as e:
            c.rollback(); return ("err", e.pgcode)
        finally: c.close()
    for rl in ("entry", "reviewer"):
        r = as_user(rl, "insert into announcements(text) values ('اختبار غير مصرح')")
        ok(r[0] == "err", f"{rl} cannot publish an announcement (RLS)")
        r = as_user(rl, "update announcements set active=false"); ok(r == ("ok", 0), f"{rl} cannot change announcements (RLS)")
        r = as_user(rl, "delete from announcements"); ok(r == ("ok", 0), f"{rl} cannot delete announcements (RLS)")
        r = as_user(rl, "select 1 from announcements"); ok(r[0] == "ok" and r[1] == 1, f"{rl} can read announcements")
    login("admin", ADMIN_PW); tab("الإعلانات")
    ev(f"{SR}.querySelector('[data-annt]').click()"); page.wait_for_timeout(500)
    ok(sql("select active from announcements") == [(False,)], "stopping an announcement is saved")
    ev(f"{SR}.querySelector('[data-annd]').click()"); ev(f"{SR}.querySelector('[data-annd]').click()"); page.wait_for_timeout(600)
    ok(sql("select count(*) from announcements") == [(0,)], "deleting an announcement is saved")
    out()

    # ---------- 6d. usage statistics (device / source / sections / assistant topics)
    login("admin", ADMIN_PW); tab("الزوار"); page.wait_for_timeout(900)
    ok("supabase_update_4.sql" in app(), "admin is told to run supabase_update_4.sql when the statistics table is missing")
    out()
    for _ in range(2): subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_4.sql")], check=True, capture_output=True)
    def rpc_as(role_sql, q, args=()):
        c = psycopg2.connect(DSN); cur = c.cursor()
        try:
            cur.execute(role_sql); cur.execute(q, args); r = cur.fetchall() if cur.description else None; c.commit(); return ("ok", r)
        except psycopg2.Error as e:
            c.rollback(); return ("err", e.pgcode)
        finally: c.close()
    ANON = "set local role anon"
    good = json.dumps([{"k":"device","v":"mobile"},{"k":"os","v":"ios"},{"k":"browser","v":"safari"},{"k":"src","v":"whatsapp"},{"k":"src","v":"whatsapp"},{"k":"ret","v":"new"},{"k":"hour","v":"21"},{"k":"sec","v":"ai"},{"k":"sec","v":"game_start"},{"k":"ask","v":"prizes"},{"k":"ask","v":"register"}])
    r = rpc_as(ANON, "select public.q29_track(%s::jsonb)", (good,)); ok(r[0] == "ok", "anonymous visitor can send anonymous counters")
    ok(sql("select n from stat_counts where kind='src' and key='whatsapp'") == [(2,)], "the same label is counted twice")
    ok(sql("select count(*) from stat_counts")[0][0] == 10, "each valid label stored once per day")
    bad = json.dumps([{"k":"device","v":"toaster"},{"k":"os","v":"<script>"},{"k":"secret","v":"x"},{"k":"hour","v":"24"},{"k":"ask","v":"my private question text"},{"k":"src","v":None},{"v":"x"}])
    rpc_as(ANON, "select public.q29_track(%s::jsonb)", (bad,)); ok(sql("select count(*) from stat_counts")[0][0] == 10, "unknown kinds and labels are ignored (no junk, no free text)")
    rpc_as(ANON, "select public.q29_track(%s::jsonb)", ("{}",)); rpc_as(ANON, "select public.q29_track(%s::jsonb)", ("null",))
    many = json.dumps([{"k":"hour","v":str(i % 24)} for i in range(200)])
    sql("delete from stat_counts"); rpc_as(ANON, "select public.q29_track(%s::jsonb)", (many,))
    ok(sql("select coalesce(sum(n),0) from stat_counts")[0][0] == 20, "at most 20 items are accepted per request")
    ok(rpc_as(ANON, "select * from public.stat_counts")[0] == "err", "anonymous cannot read the counters table")
    ok(rpc_as(ANON, "select * from public.q29_stats(30)")[0] == "err", "anonymous cannot read the statistics")
    rpc_as(ANON, "select public.q29_track(%s::jsonb)", (good,))
    uid_e = sql("select user_id::text from members where role='entry' limit 1")[0][0]
    r = rpc_as("set local role authenticated", "select count(*) from public.q29_stats(30)"); ok(r[0] == "ok" and r[1] == [(0,)] or r[0] == "err", "a user without a role gets no statistics")
    login("admin", ADMIN_PW); tab("لوحة التحكم"); page.wait_for_timeout(900)
    ok("تفاصيل زوار الدليل" in app(), "dashboard links to the visitors tab")
    tab("الزوار"); page.wait_for_timeout(1200)
    ok("supabase_update_4.sql" not in app() and "ملخص الفترة بكلمات" in app(), "visitors tab shows the story once the SQL is installed")
    ok("واتساب" in app() and "جوال" in app() and "المساعد" in app() and "الجوائز" in app(), "visitors tab shows source, device, section and assistant topic labels")
    ok("سفاري" in app() and "آيفون" in app() and "رحلة التفاعل" in app() and "خريطة ساعات الأسبوع" in app(), "visitors tab shows browser, system, funnel and heat map")
    ev(f"{SR}.querySelector('[data-vr=\"30\"]').click()"); page.wait_for_timeout(500)
    ok("30 يومًا" in app() and "ملخص الفترة بكلمات" in app(), "range switch to 30 days works")
    out()

    # ---------- 6e. announcements by audience (supabase_update_5.sql)
    login("admin", ADMIN_PW); tab("الإعلانات"); page.wait_for_timeout(700)
    ok("supabase_update_5.sql" in app(), "admin is told to run supabase_update_5.sql for visitor announcements")
    ok(ev(f"{SR}.querySelector('[data-aud=public]').disabled") is True, "visitor audience is disabled until the SQL is installed")
    out()
    for _ in range(2): subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_5.sql")], check=True, capture_output=True)
    ok(sql("select count(*) from pg_policies where tablename='announcements'") == [(2,)], "update 5 is re-runnable and keeps 2 policies")
    page.reload(); page.wait_for_timeout(500)
    login("admin", ADMIN_PW); tab("الإعلانات"); page.wait_for_timeout(700)
    ok("supabase_update_5.sql" not in app() and ev(f"{SR}.querySelector('[data-aud=public]').disabled") is False, "audience choice enabled once the SQL is installed")
    # 1) visitors only, with link
    ev(f"{SR}.querySelector('[data-aud=public]').click()"); page.wait_for_timeout(150)
    L("#annT").fill("التسجيل مفتوح للزوار الآن"); L("#annU").fill("https://example.org/x"); L("#annUL").fill("التفاصيل")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    # 2) split
    ev(f"{SR}.querySelector('[data-aud=split]').click()"); page.wait_for_timeout(150)
    L("#annT").fill("نص الزوار للخبر المشترك"); L("#annT2").fill("نص الجهات للخبر المشترك")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    # 3) scheduled for everyone (future)
    ev(f"{SR}.querySelector('[data-aud=all]').click()"); page.wait_for_timeout(150)
    L("#annT").fill("إعلان مجدول للجميع"); L("#annS").fill("2099-01-01")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    r = sql("select audience, count(*), count(distinct grp) from announcements group by audience order by audience")
    ok(r == [("all", 1, 0), ("ents", 1, 1), ("public", 2, 1)], f"rows stored with audience and group {r}")
    ok(sql("select link_url, link_label from announcements where text like 'التسجيل مفتوح%%'") == [("https://example.org/x", "التفاصيل")], "link saved")
    r = as_user("entry", "insert into announcements(text, audience) values ('x', 'public')"); ok(r[0] == "err", "entity cannot publish to visitors (RLS)")
    try:
        sql("insert into announcements(text, audience, link_url) values ('bad link', 'public', 'javascript:alert(1)')"); ok(False, "unsafe link rejected by the database")
    except psycopg2.Error: ok(True, "unsafe link rejected by the database")
    def anon_ann():
        return rpc_as(ANON, "select text from public.q29_public_ann() order by text")
    r = anon_ann(); ok(r[0] == "ok" and sorted(x[0] for x in r[1]) == sorted(["التسجيل مفتوح للزوار الآن", "نص الزوار للخبر المشترك"]), f"visitors get only live visitor announcements {r}")
    r = rpc_as(ANON, "select * from public.announcements"); ok(r[0] == "err" or r[1] == [], "anonymous gets no rows from the announcements table")
    out()
    login("noor.test", "noor1234"); t = app()
    ok("نص الجهات للخبر المشترك" in t and "نص الزوار للخبر المشترك" not in t and "التسجيل مفتوح للزوار" not in t and "إعلان مجدول" not in t, "entity sees only entity text (not visitor-only, not scheduled)")
    r = as_user("entry", "select 1 from announcements"); ok(r == ("ok", 1), f"RLS returns entity rows only {r}")
    out()
    # guide (visitor) shows the visitor texts and counts views / clicks
    page.reload(); page.wait_for_timeout(1500)
    g = ev("document.querySelector('.gann-wrap').innerText")
    ok("التسجيل مفتوح للزوار الآن" in g and "نص الزوار للخبر المشترك" in g and "نص الجهات" not in g and "مجدول" not in g, "guide home shows visitor announcements from the database")
    ev("document.querySelector('.gann-wrap a').addEventListener('click',e=>e.preventDefault())"); ev("document.querySelector('.gann-wrap a').click()")
    ev("dispatchEvent(new Event('pagehide'))"); page.wait_for_timeout(1500)
    r = sql("select kind, sum(n)::int from stat_counts where kind in ('annv','annc') group by kind order by kind")
    ok(r == [("annc", 1), ("annv", 2)], f"views and link click counted {r}")
    bad = json.dumps([{"k": "annv", "v": "00000000-0000-0000-0000-000000000000"}, {"k": "annc", "v": "not-a-uuid"}])
    rpc_as(ANON, "select public.q29_track(%s::jsonb)", (bad,))
    ok(sql("select count(*) from stat_counts where kind in ('annv','annc')") == [(3,)], "unknown announcement ids are ignored")
    login("admin", ADMIN_PW); tab("الإعلانات"); page.wait_for_timeout(900)
    ok("ظهر للزوار 1 مرة · 1 ضغطة" in app(), "admin sees views and clicks per announcement")
    ev(f"[...{SR}.querySelectorAll('.ann-it')].find(x=>x.innerText.includes('نص الجهات للخبر')).querySelector('[data-annt]').click()"); page.wait_for_timeout(800)
    ok(sql("select bool_or(active) from announcements where grp is not null") == [(False,)], "stopping a split item stops both texts")
    ok(len(anon_ann()[1]) == 1, "stopped item disappears for visitors")
    b_ = f"[...{SR}.querySelectorAll('.ann-it')].find(x=>x.innerText.includes('نص الجهات للخبر')).querySelector('[data-annd]')"
    ev(f"{b_}.click()"); ev(f"{b_}.click()"); page.wait_for_timeout(800)
    ok(sql("select count(*) from announcements where grp is not null") == [(0,)], "deleting a split item deletes both texts")
    out()

    # ---------- 6f. after-hide setting (supabase_update_6.sql)
    login("admin", ADMIN_PW); tab("الإعلانات"); page.wait_for_timeout(700)
    ok("supabase_update_6.sql" in app() and ev(f"{SR}.querySelector('#annH').disabled") is True, "after-hide choice disabled until update 6 is installed")
    out()
    for _ in range(2): subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_6.sql")], check=True, capture_output=True)
    page.reload(); page.wait_for_timeout(500)
    login("admin", ADMIN_PW); tab("الإعلانات"); page.wait_for_timeout(700)
    ok("supabase_update_6.sql" not in app() and ev(f"{SR}.querySelector('#annH').disabled") is False, "after-hide choice enabled once update 6 is installed")
    ev(f"{SR}.querySelector('[data-aud=public]').click()"); page.wait_for_timeout(150)
    L("#annH").select_option("pin"); L("#annT").fill("تنبيه مثبت للزوار")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    L("#annH").select_option("visits"); L("#annHN").fill("2"); L("#annT").fill("إعلان يعود مرتين")
    clr(); ev(f"{SR}.querySelector('#annAdd').click()"); wait_toast("نُشر الإعلان")
    r = sql("select text, hide_mode, hide_n from announcements where hide_mode <> 'never' order by text")
    ok(r == [("إعلان يعود مرتين", "visits", 2), ("تنبيه مثبت للزوار", "pin", None)], f"after-hide setting stored {r}")
    ok("يعود 2 مرة بعد الإخفاء" in app() or "يعود 2" in app(), "list shows the after-hide setting")
    for bad in ("update announcements set hide_n = 0 where hide_mode='visits'", "update announcements set hide_n = 3 where hide_mode='pin'", "update announcements set hide_mode='soon'"):
        try: sql(bad); ok(False, "database rejects invalid after-hide value: " + bad)
        except psycopg2.Error: ok(True, "database rejects invalid after-hide value")
    r = rpc_as(ANON, "select text, hide_mode, hide_n from public.q29_public_ann() order by text")
    ok(r[0] == "ok" and ("تنبيه مثبت للزوار", "pin", None) in r[1] and ("إعلان يعود مرتين", "visits", 2) in r[1], f"visitor function returns the setting {r}")
    out()
    page.reload(); page.wait_for_timeout(1500)
    pinned = ev("(()=>{const x=[...document.querySelectorAll('.gann')].find(x=>x.innerText.includes('تنبيه مثبت للزوار'));return x?!x.querySelector('[data-gannx]'):null})()")
    ok(pinned is True, "guide shows the pinned announcement without ×")
    ev("[...document.querySelectorAll('.gann')].find(x=>x.innerText.includes('إعلان يعود مرتين')).querySelector('[data-gannx]').click()"); page.wait_for_timeout(200)
    ok("إعلان يعود مرتين" not in ev("document.querySelector('.gann-wrap').innerText"), "visits announcement can be hidden")
    ok(ev("(()=>{sessionStorage.clear();Q29ANN._m=[];return localStorage.getItem('q29ax')})()") and True, "hide stored on the device")
    page.reload(); page.wait_for_timeout(1500)
    ok("إعلان يعود مرتين" in ev("document.querySelector('.gann-wrap').innerText"), "it comes back on the next visit")

    # ---------- 6g. own passwords (supabase_update_7.sql)
    login("noor.test", "noor1234")
    ok("قائمة مرشحي الجهة" in app() and not ev(f"!!{SR}.querySelector('#pwGo')"), "before update 7: no password screen and no change button")
    out()
    for _ in range(2): subprocess.run(PSQL + ["-d", "q29", "-f", os.path.join(HERE, "supabase_update_7.sql")], check=True, capture_output=True)
    ok(sql("select count(*) from members where role<>'admin' and not pw_set")[0][0] >= 2, "existing coordinator accounts must choose a password")
    page.reload(); page.wait_for_timeout(500)
    login("noor.test", "noor1234")
    ok("اختر كلمة مرور خاصة بك" in app(), "coordinator is asked to choose a password at sign-in")
    L("#pw0").fill("wrong-one"); L("#pw1").fill("NoorOwn2026"); L("#pw2").fill("NoorOwn2026"); ev(f"{SR}.querySelector('#pwSave').click()"); page.wait_for_timeout(1200)
    ok("غير صحيحة" in ev(f"{SR}.querySelector('#pwE').textContent"), "database rejects a wrong current password")
    L("#pw0").fill("noor1234"); ev(f"{SR}.querySelector('#pwSave').click()"); page.wait_for_timeout(1500)
    ok("قائمة مرشحي الجهة" in app(), "password changed, list opens")
    ok(sql("select m.pw_set from members m join entities e on e.id=m.ent_id where e.username='noor.test' and m.role='entry'") == [(True,)], "pw_set saved")
    out()
    login("noor.test", "noor1234"); ok("قائمة مرشحي الجهة" not in app(), "old password no longer works")
    L("#lu").fill("noor.test"); L("#lp").fill("NoorOwn2026"); ev(f"{SR}.querySelector('#lf').requestSubmit()"); wait_loaded()
    ok("قائمة مرشحي الجهة" in app() and ev(f"!!{SR}.querySelector('#pwGo')"), "new password works and is not asked again")
    out()
    login("admin", ADMIN_PW); tab("الجهات والمنسقون")
    rp = f"[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('noor.test')).querySelector('[data-rp]:not([data-rev])')"
    ev(f"{rp}.click()"); ev(f"{rp}.click()"); page.wait_for_timeout(1500)
    newpw = ev(f"{SR}.querySelector('.ok-note code').textContent")
    ok(len(newpw) == 8 and sql("select m.pw_set from members m join entities e on e.id=m.ent_id where e.username='noor.test' and m.role='entry'") == [(False,)], "admin reset sets a new password and asks the user to change it")
    out()
    login("noor.test", newpw); ok("اختر كلمة مرور خاصة بك" in app(), "after reset the coordinator must choose again")
    out()

    # ---------- 7. deactivated entity is locked out (+ visit counter)
    ok((sql("select coalesce(sum(n),0) from page_views")[0][0] or 0) >= 1, "the guide recorded a visit in the database")
    login("admin", ADMIN_PW); tab("لوحة التحكم"); page.wait_for_timeout(800)
    ok("إجمالي الزيارات" in app() and "زيارة اليوم" in app(), "admin dashboard shows visit counts")
    tab("الجهات والمنسقون")
    ev(f"()=>[...{SR}.querySelectorAll('#app .row')].find(r=>r.innerText.includes('مدرسة الفجر')).querySelector('[data-ee]').click()"); page.wait_for_timeout(300)
    clr(); ev(f"()=>{{const s={SR}.querySelector('#ea');s.value='0';s.dispatchEvent(new Event('change'))}}"); ev(f"{SR}.querySelector('#ef button[type=submit]').click()"); wait_toast("حُفظت التعديلات")
    out()
    login("fajr.test", "fajrNEW99"); ok("غير مفعّل" in app(), "deactivated entity cannot use the portal")
    b.close()
srv.shutdown()
print("\nPAGE ERRORS:", errors)
print("FAILS:", fails)
sys.exit(1 if fails or errors else 0)
