# entity portal: autosave, camera button, photo check, competition helper (offline copy)
from playwright.sync_api import sync_playwright
U="http://localhost:8765/ix.html";SR="document.querySelector('.pt-host').shadowRoot";fails=[]
def ok(c,m):
    print(("PASS " if c else "FAIL ")+m)
    if not c: fails.append(m)
with sync_playwright() as p:
    b=p.chromium.launch()
    def run(mobile):
        ctx=b.new_context(**({"viewport":{"width":390,"height":844},"has_touch":True,"is_mobile":True} if mobile else {"viewport":{"width":1000,"height":1000}}))
        pg=ctx.new_page();errs=[];pg.on("pageerror",lambda e:errs.append(str(e)))
        pg.route("**/*",lambda r:r.abort() if r.request.url.startswith("http") and "localhost" not in r.request.url else r.continue_())
        pg.goto(U,wait_until="domcontentloaded");pg.wait_for_timeout(500);ev=pg.evaluate;L=lambda s:pg.locator(".pt-host").locator(s)
        app=lambda:ev(f"{SR}.querySelector('#app').innerText")
        pg.click("#coordBtn");pg.wait_for_timeout(200);pg.fill("#lgU","huda");pg.fill("#lgP","huda123");pg.click("#lgGo");pg.wait_for_timeout(600)
        tag="mobile" if mobile else "desktop"
        ev(f"{SR}.querySelector('#add').click()");pg.wait_for_timeout(300)
        ok("أدخل الرقم المدني أو تاريخ الميلاد لتظهر" in app(),tag+": helper asks for birth date first")
        L("#fn").fill("سالم أحمد الكندري");L("#fc").fill("314050112345");pg.wait_for_timeout(500)
        t=app();ok("المسابقات المتاحة لعمر 12 سنة" in t,tag+": helper lists competitions for age 12")
        ok(ev(f"[...{SR}.querySelectorAll('[data-brq]')].map(b=>b.dataset.brq).join()")==ev(f"[...{SR}.querySelectorAll('#fb option')].map(o=>o.value).join()"),tag+": helper offers the same competitions as the list")
        ev(f"{SR}.querySelector('[data-brq=general]').click()");pg.wait_for_timeout(200)
        ok(ev(f"{SR}.querySelector('#fb').value")=="general" and ev(f"{SR}.querySelector('[data-brq=general]').getAttribute('aria-pressed')")=="true",tag+": clicking a competition selects it")
        ok("اختر الشريحة في العامة" in app() and ev(f"{SR}.querySelectorAll('[data-slq]').length")==5,tag+": slice cards shown")
        ev(f"{SR}.querySelector('[data-slq=j10]').click()");pg.wait_for_timeout(200)
        ok(ev(f"{SR}.querySelector('#fs').value")=="j10",tag+": clicking a slice selects it")
        ok("متبقٍ" in ev(f"{SR}.querySelector('[data-slq=j10]').innerText"),tag+": slice card shows remaining seats")
        # camera + photo check
        cam=ev(f"getComputedStyle({SR}.querySelector('.cam')).display")
        ok((cam!="none")==mobile,tag+": camera button "+("shown" if mobile else "hidden")+" ("+cam+")")
        ok(ev(f"{SR}.querySelector('.cam input').getAttribute('capture')")=="environment",tag+": camera opens the back camera")
        L('input[data-doc=cid]').first.set_input_files("/tmp/blurry.jpg");pg.wait_for_timeout(1500)
        ok("غير واضحة" in app(),tag+": blurry photo warned")
        L('input[data-doc=cid]').first.set_input_files("/tmp/small.jpg");pg.wait_for_timeout(1500)
        ok("دقة الصورة منخفضة" in app(),tag+": small photo warned")
        L('input[data-doc=cid]').first.set_input_files("/tmp/sharp.jpg");pg.wait_for_timeout(1500)
        ok(ev(f"!{SR}.querySelector('.dwarn')"),tag+": clear photo has no warning")
        ok(ev(f"{SR}.querySelector('.doc img').src.length")<400000,tag+": photo compressed ("+str(ev(f"{SR}.querySelector('.doc img').src.length"))+" chars)")
        # autosave
        pg.wait_for_timeout(700)
        ok(ev("Object.keys(localStorage).some(k=>k.startsWith('q29fd:')&&k.endsWith(':new'))"),tag+": unsaved new form kept on the device")
        ok(ev("window.__q29dirty()") is True,tag+": page warns before closing with unsaved changes")
        ev(f"{SR}.querySelector('#cancel').click()");pg.wait_for_timeout(300)
        ok("استمارة مرشح جديد لم تُحفظ" in app() and "سالم أحمد الكندري" in app(),tag+": list offers to continue the unsaved form")
        ev(f"{SR}.querySelector('#fdGo').click()");pg.wait_for_timeout(400)
        ok(ev(f"{SR}.querySelector('#fn').value")=="سالم أحمد الكندري" and ev(f"{SR}.querySelector('#fs').value")=="j10","استُعيدت البيانات" in app(),) if False else None
        ok(ev(f"{SR}.querySelector('#fn').value")=="سالم أحمد الكندري" and ev(f"{SR}.querySelector('#fs').value")=="j10" and "استُعيدت البيانات" in app(),tag+": continue restores the form")
        ev(f"{SR}.querySelector('#cancel').click()");pg.wait_for_timeout(300)
        ev(f"{SR}.querySelector('#fdDrop').click()");pg.wait_for_timeout(300)
        ok("استمارة مرشح جديد لم تُحفظ" not in app() and not ev("Object.keys(localStorage).some(k=>k.endsWith(':new'))"),tag+": unsaved form can be discarded")
        # edit existing candidate, leave, come back
        ev(f"[...{SR}.querySelectorAll('[data-edit]')][0].click()");pg.wait_for_timeout(300)
        L("#fph2").fill("22223333");pg.wait_for_timeout(700)
        ev(f"{SR}.querySelector('#cancel').click()");pg.wait_for_timeout(300)
        ev(f"[...{SR}.querySelectorAll('[data-edit]')][0].click()");pg.wait_for_timeout(300)
        ok("توجد تعديلات لم تُحفظ على هذا الجهاز" in app(),tag+": reopening shows the restore offer")
        ev(f"{SR}.querySelector('#fdR').click()");pg.wait_for_timeout(300)
        ok(ev(f"{SR}.querySelector('#fph2').value")=="22223333",tag+": restore brings the change back")
        # logout guard
        ev(f"{SR}.querySelector('#abOut').click()");pg.wait_for_timeout(300)
        ok(ev(f"!!{SR}.querySelector('#fn')") and "تسجيل الخروج مرة أخرى" in ev(f"[...{SR}.querySelectorAll('.toast')].map(t=>t.textContent).join()"),tag+": logout asks to confirm when the form has changes")
        ev(f"{SR}.querySelector('#abOut').click()");pg.wait_for_timeout(600)
        ok(not ev("Object.keys(localStorage).some(k=>k.startsWith('q29fd:'))"),tag+": logout removes unsaved forms from the device")
        # saving clears draft
        pg.click("#coordBtn");pg.wait_for_timeout(300)
        if pg.is_visible("#lgU"):
            pg.fill("#lgU","huda");pg.fill("#lgP","huda123");pg.click("#lgGo");pg.wait_for_timeout(600)
        ev(f"[...{SR}.querySelectorAll('[data-edit]')][0].click()");pg.wait_for_timeout(300)
        L("#fph2").fill("22224444");pg.wait_for_timeout(700)
        ok(ev("Object.keys(localStorage).some(k=>k.startsWith('q29fd:'))"),tag+": edit kept on device")
        ev(f"{SR}.querySelector('#cf button[type=submit]').click()");pg.wait_for_timeout(500)
        ok(not ev("Object.keys(localStorage).some(k=>k.startsWith('q29fd:'))"),tag+": saving removes the local copy")
        ok(not errs,tag+": no page errors "+str(errs))
        pg.screenshot(path=f"/tmp/f_{tag}.png");ctx.close()
    run(False);run(True)
    b.close()
print("FAILS:",fails)
